name: Step 2, Prepare to collaborate

on:
  push:
    branches:
      - prepare-to-collaborate

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_3_FILE: ".github/steps/3-foster-healthy-growth.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.1.0

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Update comment - checking work
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file skills-response-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # START: Check practical exercise
      - name: Check for CONTRIBUTING.md
        id: check-contributing
        run: |
          if [ ! -f "CONTRIBUTING.md" ]; then
            echo "result=missing" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          if ! grep -q "Development Setup" "CONTRIBUTING.md" || \
             ! grep -q "Making Changes" "CONTRIBUTING.md" || \
             ! grep -q "Code Style" "CONTRIBUTING.md"; then
            echo "result=incomplete" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "result=complete" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Check for CODEOWNERS
        id: check-codeowners
        run: |
          if [ ! -f "CODEOWNERS" ]; then
            echo "result=missing" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          if ! grep -q "/src/app.py" "CODEOWNERS" || \
             ! grep -q "/src/models/" "CODEOWNERS" || \
             ! grep -q "/src/static/" "CODEOWNERS"; then
            echo "result=incomplete" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          echo "result=complete" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Generate results table
        id: results
        run: |
          echo "table<<EOF" >> $GITHUB_OUTPUT
          echo "| Task | Result |" >> $GITHUB_OUTPUT
          echo "|------|--------|" >> $GITHUB_OUTPUT
          echo "| CONTRIBUTING.md | ${{ steps.check-contributing.outputs.result == 'complete' && '✓' || '✗' }} |" >> $GITHUB_OUTPUT
          echo "| CODEOWNERS | ${{ steps.check-codeowners.outputs.result == 'complete' && '✓' || '✗' }} |" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          if [ "${{ steps.check-contributing.outputs.result }}" != "complete" ] || \
             [ "${{ steps.check-codeowners.outputs.result }}" != "complete" ]; then
            echo "failed=true" >> $GITHUB_OUTPUT
            
            echo "message<<EOF" >> $GITHUB_OUTPUT
            if [ "${{ steps.check-contributing.outputs.result }}" == "missing" ]; then
              echo "I don't see a CONTRIBUTING.md file. Did you create it in the prepare-to-collaborate branch?" >> $GITHUB_OUTPUT
            elif [ "${{ steps.check-contributing.outputs.result }}" == "incomplete" ]; then
              echo "The CONTRIBUTING.md file is missing some required sections. Make sure it has Development Setup, Making Changes, and Code Style sections." >> $GITHUB_OUTPUT
            fi
            
            if [ "${{ steps.check-codeowners.outputs.result }}" == "missing" ]; then
              echo "I don't see a CODEOWNERS file. Did you create it in the prepare-to-collaborate branch?" >> $GITHUB_OUTPUT
            elif [ "${{ steps.check-codeowners.outputs.result }}" == "incomplete" ]; then
              echo "The CODEOWNERS file is missing some required paths. Make sure to include /src/app.py, /src/models/, and /src/static/" >> $GITHUB_OUTPUT
            fi
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      # END: Check practical exercise

      - name: Build message - step finished
        if: ${{ !steps.results.outputs.failed }}
        id: build-message-step-finish
        uses: skills/action-text-variables@v1
        with:
          template-file: skills-response-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number=3

      - name: Build message - step failed
        if: ${{ steps.results.outputs.failed }}
        id: build-message-step-failed
        uses: skills/action-text-variables@v1
        with:
          template-file: skills-response-templates/step-feedback/step-mistake.md
          template-vars: |
            table=${{ steps.results.outputs.table }}
            step_number=2
            message=${{ steps.results.outputs.message }}

      - name: Update comment - step status
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$ISSUE_BODY" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.results.outputs.failed && steps.build-message-step-failed.outputs.updated-text || steps.build-message-step-finish.outputs.updated-text }}

  post_next_step_content:
    name: Post next step content
    if: ${{ needs.check_step_work.result == 'success' }}
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/response-templates
          path: skills-response-templates

      - name: Create comment - add step content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$STEP_3_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create comment - watching for progress
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file skills-response-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable current workflow and enable next one
        run: |
          gh workflow disable "Step 2"
          gh workflow enable "Step 3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
